apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy
      env: dev
  template:
    metadata:
      labels:
        app: swiggy
        env: dev
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
        - name: mycont
          image: ponugotikava/dockerjenkins:jenkinsimage
          ports:
            - containerPort: 80

